# Generated by Django 6.0.4 on 2026-05-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('private', 'Private Tour'), ('offroad', '4x4 Offroad'), ('boat', 'Boat Trip')], default='private', max_length=20)),
                ('badge', models.CharField(blank=True, choices=[('Bestseller', 'Bestseller'), ('Relaxation', 'Relaxation'), ('Adventure', 'Adventure'), ('New', 'New'), ('Popular', 'Popular'), ('', 'None')], default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_label', models.CharField(default='/ person', max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('group_size', models.CharField(max_length=50)),
                ('main_image', models.ImageField(upload_to='tours/')),
                ('whatsapp_number', models.CharField(default='355686033460', max_length=20)),
                ('min_guests', models.PositiveIntegerField(default=2)),
                ('max_guests', models.PositiveIntegerField(default=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='albay_travel.tour')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
