# Generated by Django 6.0.4 on 2026-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albay_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_label',
            field=models.CharField(blank=True, default='/ person', max_length=50),
        ),
    ]
