# Generated by Django 6.0.4 on 2026-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albay_travel', '0002_alter_tour_price_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(default='private', help_text="Space-separated categories e.g. 'private offroad' or 'private boat'", max_length=50),
        ),
    ]
