# Generated by Django 6.0.4 on 2026-06-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albay_travel', '0003_alter_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='important_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
    ]
