# Generated by Django 6.0.4 on 2026-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albay_travel', '0004_tour_highlights_tour_important_info_tour_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('private', 'Private Tour'), ('offroad', '4x4 Offroad'), ('boat', 'Boat Trip')], default='private', max_length=50),
        ),
    ]
